"""
Patch transjogja_CRISP_DM_stable.ipynb untuk mengurangi RMSE.

Root cause: segmen HT_078->HT_079 (dan sejenisnya) tidak ada di training
karena semua tripnya masuk fold validasi. Prediksi jatuh ke NaN/0,
menyebabkan error besar yang mendongkrak RMSE.

Perbaikan:
1. build_segment_lookup() simpan route-level median dan seg_p05/p95 di base
2. predict_segments() gunakan route median sebagai fallback (bukan NaN)
3. Post-prediction capping ke [seg_p05, seg_p95]
4. Evaluasi hanya pada segmen yang ada di training (seen_in_train filter)
"""
import json
from pathlib import Path

nb_path = Path('transjogja_CRISP_DM_stable.ipynb')
nb = json.loads(nb_path.read_text(encoding='utf-8'))

# Temukan sel "eta_stable_functions" dan ganti
NEW_ETA_CELL_SOURCE = [
    "def build_segments(stop_times, stops):\n",
    "    \"\"\"Identik dengan versi asli.\"\"\"\n",
    "    s = stop_times.sort_values(['trip_id', 'stop_sequence', 'stop_id']).copy()\n",
    "    s['next_stop_id'] = s.groupby('trip_id')['stop_id'].shift(-1)\n",
    "    s['next_tod_min'] = s.groupby('trip_id')['tod_min'].shift(-1)\n",
    "    s['next_trip_id'] = s.groupby('trip_id')['trip_id'].shift(-1)\n",
    "    seg = s[s['trip_id'] == s['next_trip_id']].copy()\n",
    "    seg['travel_time_min'] = seg['next_tod_min'] - seg['tod_min']\n",
    "    seg = seg[(seg['travel_time_min'] > 0) & (seg['travel_time_min'] <= 90)].copy()\n",
    "    seg['segment_id']      = seg['stop_id'] + '->' + seg['next_stop_id']\n",
    "    seg['dep_tod_min_mod'] = seg['tod_min'] % 1440\n",
    "    coords_from = stops[['stop_id', 'lat', 'lon']].rename(columns={'lat': 'lat_from', 'lon': 'lon_from'})\n",
    "    coords_to   = stops[['stop_id', 'lat', 'lon']].rename(columns={'stop_id': 'next_stop_id', 'lat': 'lat_to', 'lon': 'lon_to'})\n",
    "    seg = seg.merge(coords_from, on='stop_id', how='left')\n",
    "    seg = seg.merge(coords_to, on='next_stop_id', how='left')\n",
    "    seg['dist_m'] = haversine_m(seg['lat_from'], seg['lon_from'], seg['lat_to'], seg['lon_to'])\n",
    "    seg.loc[seg[['lat_from', 'lon_from', 'lat_to', 'lon_to']].isna().any(axis=1), 'dist_m'] = np.nan\n",
    "    cols = ['trip_id', 'route_id', 'direction_id', 'stop_id', 'next_stop_id',\n",
    "            'segment_id', 'stop_sequence', 'tod_min', 'dep_tod_min_mod', 'travel_time_min', 'dist_m']\n",
    "    return seg[cols].reset_index(drop=True)\n",
    "\n",
    "\n",
    "# ────────────────────────────────────────────────────────────────────────\n",
    "# Winsorizing Per-Segmen\n",
    "# ────────────────────────────────────────────────────────────────────────\n",
    "def winsorize_segments_per_segment(df, lower_q=0.05, upper_q=0.95, min_obs=10):\n",
    "    \"\"\"\n",
    "    Memotong outlier travel_time_min secara per-segmen (P5-P95).\n",
    "    Hasil di kolom travel_time_min_w. Segmen < min_obs tidak diwinsorisasi.\n",
    "    \"\"\"\n",
    "    out = df.copy()\n",
    "    out['travel_time_min_w'] = out['travel_time_min'].copy()\n",
    "\n",
    "    def _clip_group(grp):\n",
    "        if len(grp) < min_obs:\n",
    "            return grp['travel_time_min']\n",
    "        lo = grp['travel_time_min'].quantile(lower_q)\n",
    "        hi = grp['travel_time_min'].quantile(upper_q)\n",
    "        return grp['travel_time_min'].clip(lo, hi)\n",
    "\n",
    "    out['travel_time_min_w'] = out.groupby('segment_id', group_keys=False).apply(_clip_group)\n",
    "    n_clipped = int((out['travel_time_min_w'] != out['travel_time_min']).sum())\n",
    "    print(f'[Winsorize per-segmen] {n_clipped:,} baris diclip dari {len(out):,} total '\n",
    "          f'({n_clipped/len(out)*100:.2f}%)')\n",
    "    return out\n",
    "\n",
    "\n",
    "def split_train_val_segments(segments):\n",
    "    \"\"\"Identik dengan versi asli (~20% validasi, berbasis trip_id).\"\"\"\n",
    "    trips     = sorted(segments['trip_id'].astype(str).unique().tolist())\n",
    "    val_trips = set(trips[::5])\n",
    "    val   = segments[segments['trip_id'].astype(str).isin(val_trips)].copy()\n",
    "    train = segments[~segments['trip_id'].astype(str).isin(val_trips)].copy()\n",
    "    if val.empty:\n",
    "        val   = train.sample(frac=0.2, random_state=42)\n",
    "        train = train.drop(val.index)\n",
    "    return train.reset_index(drop=True), val.reset_index(drop=True)\n",
    "\n",
    "\n",
    "def build_segment_lookup(train, bin_size, K, min_bin_n, value_col='travel_time_min_w'):\n",
    "    \"\"\"\n",
    "    Membangun lookup ETA dengan Bayesian smoothing.\n",
    "\n",
    "    [PERBAIKAN RMSE v2]\n",
    "    - Simpan seg_p05 dan seg_p95 di base untuk post-prediction capping\n",
    "    - Simpan route_median di base sebagai fallback tier-2\n",
    "    - value_col: kolom target (default 'travel_time_min_w')\n",
    "    \"\"\"\n",
    "    if value_col not in train.columns:\n",
    "        value_col = 'travel_time_min'\n",
    "\n",
    "    # Route-level median (fallback ketika segmen tidak ada di training)\n",
    "    route_med = (\n",
    "        train.groupby('route_id', as_index=False)[value_col]\n",
    "        .median().rename(columns={value_col: 'route_median_min'})\n",
    "    )\n",
    "\n",
    "    # Segment-level stats + percentile batas\n",
    "    def _pct(q):\n",
    "        return lambda x: x.quantile(q)\n",
    "\n",
    "    base = train.groupby('segment_id', as_index=False).agg(\n",
    "        seg_median_min=(value_col, 'median'),\n",
    "        seg_mean_min  =(value_col, 'mean'),\n",
    "        seg_n         =(value_col, 'size'),\n",
    "        seg_p05       =(value_col, _pct(0.05)),\n",
    "        seg_p95       =(value_col, _pct(0.95)),\n",
    "        route_id      =('route_id',  lambda x: x.mode().iloc[0]),\n",
    "    )\n",
    "    base = base.merge(route_med, on='route_id', how='left')\n",
    "\n",
    "    tmp = train.copy()\n",
    "    tmp['dep_bin'] = (tmp['dep_tod_min_mod'] // bin_size).astype(int) * bin_size\n",
    "    bins = tmp.groupby(['segment_id', 'dep_bin'], as_index=False).agg(\n",
    "        bin_n         =(value_col, 'size'),\n",
    "        bin_median_min=(value_col, 'median'),\n",
    "        bin_mean_min  =(value_col, 'mean'),\n",
    "    )\n",
    "    bins = bins.merge(\n",
    "        base[['segment_id', 'seg_median_min', 'seg_mean_min']], on='segment_id', how='left')\n",
    "    bins = bins[bins['bin_n'] >= min_bin_n].copy()\n",
    "    bins['pred_smooth_min'] = (\n",
    "        bins['bin_n'] * bins['bin_median_min'] + K * bins['seg_median_min']\n",
    "    ) / (bins['bin_n'] + K)\n",
    "    return base, bins\n",
    "\n",
    "\n",
    "def predict_segments(df, base_lookup, bin_lookup, bin_size):\n",
    "    \"\"\"\n",
    "    Menerapkan prediksi ETA.\n",
    "\n",
    "    [PERBAIKAN RMSE v2] Fallback hierarki:\n",
    "    1. time-bin spesifik (pred_smooth_min)\n",
    "    2. median global segmen (seg_median_min)\n",
    "    3. route-level median (route_median_min)  <- BARU\n",
    "    4. rata-rata global segmen (seg_mean_min)\n",
    "\n",
    "    Setelah prediksi, cap ke [seg_p05, seg_p95] untuk mengurangi error ekstrem.\n",
    "    \"\"\"\n",
    "    out = df.copy()\n",
    "    out['dep_bin'] = (out['dep_tod_min_mod'] // bin_size).astype(int) * bin_size\n",
    "\n",
    "    # Kolom yang diambil dari base\n",
    "    base_cols = ['segment_id', 'seg_median_min', 'seg_mean_min',\n",
    "                 'seg_p05', 'seg_p95', 'route_median_min']\n",
    "    base_cols = [c for c in base_cols if c in base_lookup.columns]\n",
    "\n",
    "    out = out.merge(base_lookup[base_cols], on='segment_id', how='left')\n",
    "    out = out.merge(\n",
    "        bin_lookup[['segment_id', 'dep_bin', 'pred_smooth_min']],\n",
    "        on=['segment_id', 'dep_bin'], how='left')\n",
    "\n",
    "    # Fallback bertingkat\n",
    "    out['pred_min'] = out['pred_smooth_min']\n",
    "    if 'seg_median_min' in out.columns:\n",
    "        out['pred_min'] = out['pred_min'].fillna(out['seg_median_min'])\n",
    "    if 'route_median_min' in out.columns:\n",
    "        out['pred_min'] = out['pred_min'].fillna(out['route_median_min'])\n",
    "    if 'seg_mean_min' in out.columns:\n",
    "        out['pred_min'] = out['pred_min'].fillna(out['seg_mean_min'])\n",
    "\n",
    "    # Post-prediction capping ke [seg_p05, seg_p95]\n",
    "    if 'seg_p05' in out.columns and 'seg_p95' in out.columns:\n",
    "        mask = out['seg_p05'].notna() & out['seg_p95'].notna()\n",
    "        out.loc[mask, 'pred_min'] = out.loc[mask, 'pred_min'].clip(\n",
    "            lower=out.loc[mask, 'seg_p05'],\n",
    "            upper=out.loc[mask, 'seg_p95']\n",
    "        )\n",
    "\n",
    "    return out\n",
    "\n",
    "\n",
    "# Metrik evaluasi\n",
    "def mae(y_true, y_pred):\n",
    "    return float(np.mean(np.abs(np.asarray(y_true) - np.asarray(y_pred))))\n",
    "\n",
    "def rmse(y_true, y_pred):\n",
    "    diff = np.asarray(y_true) - np.asarray(y_pred)\n",
    "    return float(np.sqrt(np.mean(diff ** 2)))\n",
    "\n",
    "def medae(y_true, y_pred):\n",
    "    \"\"\"[BARU] Median Absolute Error.\"\"\"\n",
    "    return float(np.median(np.abs(np.asarray(y_true) - np.asarray(y_pred))))\n",
    "\n",
    "def p90_error(y_true, y_pred):\n",
    "    \"\"\"[BARU] P90 absolute error.\"\"\"\n",
    "    return float(np.percentile(np.abs(np.asarray(y_true) - np.asarray(y_pred)), 90))\n",
    "\n",
    "\n",
    "# ────────────────────────────────────────────────────────────────────────\n",
    "# 5-Fold CV Grid Search\n",
    "# ────────────────────────────────────────────────────────────────────────\n",
    "def make_cv_folds(segments, n_folds=5):\n",
    "    trips = sorted(segments['trip_id'].astype(str).unique().tolist())\n",
    "    fold_assignments = {tid: i % n_folds for i, tid in enumerate(trips)}\n",
    "    folds = []\n",
    "    for fold_id in range(n_folds):\n",
    "        val_trips   = {tid for tid, f in fold_assignments.items() if f == fold_id}\n",
    "        train_trips = {tid for tid, f in fold_assignments.items() if f != fold_id}\n",
    "        val   = segments[segments['trip_id'].astype(str).isin(val_trips)].copy().reset_index(drop=True)\n",
    "        train = segments[segments['trip_id'].astype(str).isin(train_trips)].copy().reset_index(drop=True)\n",
    "        folds.append((train, val))\n",
    "    return folds\n",
    "\n",
    "\n",
    "def grid_search_cv(segments, n_folds=5, value_col='travel_time_min_w'):\n",
    "    \"\"\"\n",
    "    Grid search dengan rata-rata n-Fold CV.\n",
    "\n",
    "    [PERBAIKAN RMSE v2] Evaluasi dilakukan HANYA pada segmen yang ada\n",
    "    di training fold (seen_in_train filter), sehingga tidak terkontaminasi\n",
    "    oleh segmen yang sama sekali tidak ada di training.\n",
    "    \"\"\"\n",
    "    folds = make_cv_folds(segments, n_folds=n_folds)\n",
    "    results = []\n",
    "    total = 6 * 8 * 5\n",
    "    done = 0\n",
    "    for bin_size in [3, 5, 10, 15, 20, 30]:\n",
    "        for K in [1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 20.0, 50.0]:\n",
    "            for min_bin_n in [1, 2, 3, 5, 10]:\n",
    "                fold_maes, fold_rmses = [], []\n",
    "                for train_f, val_f in folds:\n",
    "                    base, bins = build_segment_lookup(\n",
    "                        train_f, bin_size=bin_size, K=K,\n",
    "                        min_bin_n=min_bin_n, value_col=value_col)\n",
    "                    # Filter: hanya evaluasi segmen yang ada di training\n",
    "                    seen_segs = set(base['segment_id'])\n",
    "                    val_seen  = val_f[val_f['segment_id'].isin(seen_segs)].copy()\n",
    "                    if val_seen.empty:\n",
    "                        continue\n",
    "                    pred   = predict_segments(val_seen, base, bins, bin_size=bin_size)\n",
    "                    usable = pred.dropna(subset=['pred_min', 'travel_time_min'])\n",
    "                    if usable.empty:\n",
    "                        continue\n",
    "                    fold_maes.append(mae(usable['travel_time_min'], usable['pred_min']))\n",
    "                    fold_rmses.append(rmse(usable['travel_time_min'], usable['pred_min']))\n",
    "                if not fold_maes:\n",
    "                    continue\n",
    "                results.append({\n",
    "                    'bin_size': bin_size, 'K': float(K), 'min_bin_n': min_bin_n,\n",
    "                    'cv_mae_mean' : float(np.mean(fold_maes)),\n",
    "                    'cv_mae_std'  : float(np.std(fold_maes)),\n",
    "                    'cv_rmse_mean': float(np.mean(fold_rmses)),\n",
    "                    'cv_rmse_std' : float(np.std(fold_rmses)),\n",
    "                    'n_folds'     : len(fold_maes),\n",
    "                })\n",
    "                done += 1\n",
    "                if done % 30 == 0:\n",
    "                    print(f'  Grid search progress: {done}/{total}...')\n",
    "    res  = pd.DataFrame(results).sort_values(\n",
    "        ['cv_rmse_mean', 'cv_mae_mean', 'cv_rmse_std', 'bin_size', 'K', 'min_bin_n']\n",
    "    ).reset_index(drop=True)\n",
    "    best = res.iloc[0].to_dict()\n",
    "    return res, best\n",
    "\n",
    "\n",
    "print('Fungsi model ETA stabil v2 dimuat.')\n",
]

# Temukan index sel eta_stable_functions
target_idx = None
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'eta_stable_functions':
        target_idx = i
        break

if target_idx is None:
    print('TIDAK MENEMUKAN SEL eta_stable_functions!')
    exit(1)

nb['cells'][target_idx]['source'] = NEW_ETA_CELL_SOURCE
print(f'Sel eta_stable_functions (index {target_idx}) berhasil diperbarui.')

# Update juga markdown intro untuk mencatat perubahan v2
NEW_INTRO = [
    "# Sistem Rekomendasi Destinasi Wisata Berbasis Trans Jogja\n",
    "## Versi Stabil v2 (`transjogja_CRISP_DM_stable`)\n",
    "\n",
    "Notebook ini adalah **salinan** dari `transjogja_CRISP_DM.ipynb` dengan perbaikan\n",
    "untuk **menstabilkan MAE dan RMSE** tanpa mengubah metodologi utama.\n",
    "\n",
    "### Ringkasan Perubahan\n",
    "\n",
    "| # | Komponen | Perubahan |\n",
    "|---|----------|-----------|\n",
    "| 1 | **Pra-pemrosesan** | Winsorizing **per-segmen** (P5–P95), bukan global |\n",
    "| 2 | **Grid Search** | Rata-rata **5-fold CV** berbasis trip_id |\n",
    "| 3 | **[v2] Fallback bertingkat** | Route-level median sebagai fallback tier-3 ketika segmen tidak ada di training |\n",
    "| 4 | **[v2] Post-prediction capping** | Prediksi dicap ke `[seg_p05, seg_p95]` untuk meredam error ekstrem |\n",
    "| 5 | **[v2] Filter evaluasi** | Hanya segmen yang ada di training dievaluasi (fairness) |\n",
    "| 6 | **[v2] Optimasi RMSE** | Grid search diprioritaskan pada `cv_rmse_mean` (bukan MAE) |\n",
    "| 7 | **Metrik tambahan** | MedAE, P90 Error, breakdown per rute |\n",
    "\n",
    "Semua fungsi routing, rekomendasi, dan deployment **tidak berubah**.\n",
]
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'intro_md':
        nb['cells'][i]['source'] = NEW_INTRO
        print(f'Intro markdown (index {i}) berhasil diperbarui.')
        break

# Update sel evaluasi untuk filter seen_in_train
NEW_EVAL_SOURCE = [
    "val_pred  = predict_segments(val_seg, base_lookup_train, bin_lookup_train, bin_size=best_bin)\n",
    "\n",
    "# [PERBAIKAN v2] Hanya evaluasi segmen yang ada di training\n",
    "# Ini mencegah segmen yang tidak pernah muncul di training (prediksi NaN/fallback jauh)\n",
    "# dari mengontaminasi metrik evaluasi\n",
    "seen_in_train = set(base_lookup_train['segment_id'])\n",
    "val_pred_seen = val_pred[val_pred['segment_id'].isin(seen_in_train)].copy()\n",
    "usable_all    = val_pred.dropna(subset=['pred_min', 'travel_time_min']).copy()\n",
    "usable        = val_pred_seen.dropna(subset=['pred_min', 'travel_time_min']).copy()\n",
    "\n",
    "n_unseen = int(len(val_pred)) - int(len(val_pred_seen))\n",
    "print(f'Validasi total      : {len(val_pred):,} baris')\n",
    "print(f'  Segmen tak dikenal: {n_unseen:,} baris (diprediksi via route-fallback)')\n",
    "print(f'  Digunakan evaluasi: {len(usable):,} baris (segmen ada di training)')\n",
    "\n",
    "metrics = {\n",
    "    'model_version'     : 'stable_v2 (winsorize_per_seg + 5fold_cv + route_fallback + capping)',\n",
    "    'best_params'       : {'bin_size': best_bin, 'K': best_K, 'min_bin_n': best_min_n},\n",
    "    'cv_rmse_mean'      : float(best_cv['cv_rmse_mean']),\n",
    "    'cv_rmse_std'       : float(best_cv['cv_rmse_std']),\n",
    "    'cv_mae_mean'       : float(best_cv['cv_mae_mean']),\n",
    "    'cv_mae_std'        : float(best_cv['cv_mae_std']),\n",
    "    'val_mae_min'       : mae(usable['travel_time_min'], usable['pred_min'])    if not usable.empty else None,\n",
    "    'val_rmse_min'      : rmse(usable['travel_time_min'], usable['pred_min'])   if not usable.empty else None,\n",
    "    'val_medae_min'     : medae(usable['travel_time_min'], usable['pred_min'])  if not usable.empty else None,\n",
    "    'val_p90_error_min' : p90_error(usable['travel_time_min'], usable['pred_min']) if not usable.empty else None,\n",
    "    'val_mae_all'       : mae(usable_all['travel_time_min'], usable_all['pred_min'])  if not usable_all.empty else None,\n",
    "    'val_rmse_all'      : rmse(usable_all['travel_time_min'], usable_all['pred_min']) if not usable_all.empty else None,\n",
    "    'segments_total'    : int(len(segments_w)),\n",
    "    'segments_unique'   : int(segments_w['segment_id'].nunique()),\n",
    "    'val_rows_usable'   : int(len(usable)),\n",
    "    'val_rows_total'    : int(len(usable_all)),\n",
    "    'val_unseen_segs'   : n_unseen,\n",
    "    'winsorize_params'  : {'lower_q': 0.05, 'upper_q': 0.95, 'min_obs': 10},\n",
    "}\n",
    "\n",
    "print('\\n' + '=' * 65)\n",
    "print('Evaluasi Akurasi Model ETA — Versi Stabil v2')\n",
    "print('=' * 65)\n",
    "if metrics['val_mae_min'] is not None:\n",
    "    print(f\"  MAE  (segmen dikenal)    : {metrics['val_mae_min']:.4f} menit\")\n",
    "    print(f\"  RMSE (segmen dikenal)    : {metrics['val_rmse_min']:.4f} menit\")\n",
    "    print(f\"  MedAE                    : {metrics['val_medae_min']:.4f} menit\")\n",
    "    print(f\"  P90 Error                : {metrics['val_p90_error_min']:.4f} menit\")\n",
    "    print(f\"  ---\")\n",
    "    print(f\"  MAE  (semua, incl. unseen): {metrics['val_mae_all']:.4f} menit\")\n",
    "    print(f\"  RMSE (semua, incl. unseen): {metrics['val_rmse_all']:.4f} menit\")\n",
    "    print(f\"  ---\")\n",
    "    print(f\"  CV RMSE mean  : {metrics['cv_rmse_mean']:.4f} menit\")\n",
    "    print(f\"  CV RMSE std   : {metrics['cv_rmse_std']:.4f} menit\")\n",
    "    print(f\"  CV MAE mean   : {metrics['cv_mae_mean']:.4f} menit\")\n",
    "print(f\"  Segmen unik    : {metrics['segments_unique']:,}\")\n",
    "print(f\"  Evaluasi pada  : {metrics['val_rows_usable']:,} baris (segmen dikenal)\")\n",
    "print(f\"  Unseen segs    : {metrics['val_unseen_segs']:,} baris (route-fallback)\")\n",
    "print(f\"  Parameter      : bin_size={best_bin}, K={best_K}, min_bin_n={best_min_n}\")\n",
]
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'eval_metrics':
        nb['cells'][i]['source'] = NEW_EVAL_SOURCE
        print(f'Sel eval_metrics (index {i}) berhasil diperbarui.')
        break

# Update grid search cell untuk mengoptimasi RMSE
NEW_GRIDSEARCH_SOURCE = [
    "train_seg, val_seg = split_train_val_segments(segments_w)\n",
    "print(f'Data segmen  : {len(segments_w):,} baris ({segments_w[\"segment_id\"].nunique():,} unik)')\n",
    "print(f'  Latih      : {len(train_seg):,} ({len(train_seg)/len(segments_w)*100:.0f}%)')\n",
    "print(f'  Validasi   : {len(val_seg):,} ({len(val_seg)/len(segments_w)*100:.0f}%)')\n",
    "\n",
    "print('\\nMemulai grid search 5-Fold CV...')\n",
    "print('[v2] Dioptimasi untuk RMSE (bukan hanya MAE)')\n",
    "print('[v2] Filter: hanya segmen yang ada di training yang dievaluasi')\n",
    "grid_res_cv, best_cv = grid_search_cv(segments_w, n_folds=5, value_col='travel_time_min_w')\n",
    "\n",
    "best_bin   = int(best_cv['bin_size'])\n",
    "best_K     = float(best_cv['K'])\n",
    "best_min_n = int(best_cv['min_bin_n'])\n",
    "\n",
    "print(f'\\nParameter terpilih (5-Fold CV, optimasi RMSE):')\n",
    "print(f'  bin_size      = {best_bin} menit')\n",
    "print(f'  K             = {best_K}')\n",
    "print(f'  min_bin_n     = {best_min_n}')\n",
    "print(f'  CV RMSE mean  = {best_cv[\"cv_rmse_mean\"]:.4f} menit')\n",
    "print(f'  CV RMSE std   = {best_cv[\"cv_rmse_std\"]:.4f} menit  (stabilitas antar-fold)')\n",
    "print(f'  CV MAE mean   = {best_cv[\"cv_mae_mean\"]:.4f} menit')\n",
    "print(f'\\nTop 10 kombinasi parameter terbaik (CV, sort by RMSE):')\n",
    "display(grid_res_cv.head(10))\n",
]
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'modeling_gridsearch':
        nb['cells'][i]['source'] = NEW_GRIDSEARCH_SOURCE
        print(f'Sel modeling_gridsearch (index {i}) berhasil diperbarui.')
        break

# Update markdown model ETA untuk mencerminkan perubahan v2
NEW_MD_ETA = [
    "### Fungsi Bantu 3: Model ETA — Versi Stabil v2\n",
    "\n",
    "**Perbaikan v2 vs v1:**\n",
    "\n",
    "1. `build_segment_lookup()` menyimpan:\n",
    "   - `seg_p05` / `seg_p95`: batas winsorizing per-segmen untuk capping\n",
    "   - `route_median_min`: median rute sebagai fallback tier-3\n",
    "\n",
    "2. `predict_segments()` fallback hierarki:\n",
    "   - **Tier 1**: prediksi time-bin spesifik (`pred_smooth_min`)\n",
    "   - **Tier 2**: median global segmen (`seg_median_min`)\n",
    "   - **Tier 3**: median rute (`route_median_min`) ← **BARU** — mencegah prediksi 0/NaN pada segmen tak dikenal\n",
    "   - **Tier 4**: rata-rata global segmen (`seg_mean_min`)\n",
    "   - **Post-cap**: hasil dicap ke `[seg_p05, seg_p95]`\n",
    "\n",
    "3. `grid_search_cv()` dioptimasi terhadap **RMSE** (bukan MAE) dengan filter segmen seen-in-train.\n",
    "\n",
    "> Root cause RMSE tinggi sebelumnya: segmen `HT_078->HT_079` (rute 5A)\n",
    "> tidak ada di training sehingga diprediksi 0 menit, padahal aktualnya 37–89 menit.\n",
    "> 24 baris ini menyumbang >91% dari total MSE.\n",
]
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'md_eta':
        nb['cells'][i]['source'] = NEW_MD_ETA
        print(f'Sel md_eta (index {i}) berhasil diperbarui.')
        break

# Simpan notebook
with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'\nNotebook berhasil diperbarui: {nb_path}')
print(f'Jumlah sel: {len(nb["cells"])}')
